// default package
// Generated Sep 8, 2020 6:03:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAccSerBalManager generated by hbm2java
 */
@Entity
@Table(name = "TBL_ACC_SER_BAL_MANAGER")
public class TblAccSerBalManager implements java.io.Serializable {

	private BigDecimal accServiceId;
	private BigDecimal accId;
	private BigDecimal serviceId;
	private BigDecimal balance;
	private Date createdAt;
	private BigDecimal holdingBalance;
	private Date latestUpdate;
	private String balanceChain;
	private Date latestUpdateHolding;
	private String holdingChain;
	private String balStackCode;

	public TblAccSerBalManager() {
	}

	public TblAccSerBalManager(BigDecimal accServiceId, BigDecimal accId, BigDecimal serviceId, BigDecimal balance,
			String balanceChain) {
		this.accServiceId = accServiceId;
		this.accId = accId;
		this.serviceId = serviceId;
		this.balance = balance;
		this.balanceChain = balanceChain;
	}

	public TblAccSerBalManager(BigDecimal accServiceId, BigDecimal accId, BigDecimal serviceId, BigDecimal balance,
			Date createdAt, BigDecimal holdingBalance, Date latestUpdate, String balanceChain, Date latestUpdateHolding,
			String holdingChain, String balStackCode) {
		this.accServiceId = accServiceId;
		this.accId = accId;
		this.serviceId = serviceId;
		this.balance = balance;
		this.createdAt = createdAt;
		this.holdingBalance = holdingBalance;
		this.latestUpdate = latestUpdate;
		this.balanceChain = balanceChain;
		this.latestUpdateHolding = latestUpdateHolding;
		this.holdingChain = holdingChain;
		this.balStackCode = balStackCode;
	}

	@Id

	@Column(name = "ACC_SERVICE_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getAccServiceId() {
		return this.accServiceId;
	}

	public void setAccServiceId(BigDecimal accServiceId) {
		this.accServiceId = accServiceId;
	}

	@Column(name = "ACC_ID", nullable = false, precision = 0)
	public BigDecimal getAccId() {
		return this.accId;
	}

	public void setAccId(BigDecimal accId) {
		this.accId = accId;
	}

	@Column(name = "SERVICE_ID", nullable = false, precision = 0)
	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "BALANCE", nullable = false, precision = 0)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_AT", length = 7)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "HOLDING_BALANCE", precision = 0)
	public BigDecimal getHoldingBalance() {
		return this.holdingBalance;
	}

	public void setHoldingBalance(BigDecimal holdingBalance) {
		this.holdingBalance = holdingBalance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_UPDATE", length = 7)
	public Date getLatestUpdate() {
		return this.latestUpdate;
	}

	public void setLatestUpdate(Date latestUpdate) {
		this.latestUpdate = latestUpdate;
	}

	@Column(name = "BALANCE_CHAIN", nullable = false, length = 50)
	public String getBalanceChain() {
		return this.balanceChain;
	}

	public void setBalanceChain(String balanceChain) {
		this.balanceChain = balanceChain;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_UPDATE_HOLDING", length = 7)
	public Date getLatestUpdateHolding() {
		return this.latestUpdateHolding;
	}

	public void setLatestUpdateHolding(Date latestUpdateHolding) {
		this.latestUpdateHolding = latestUpdateHolding;
	}

	@Column(name = "HOLDING_CHAIN", length = 50)
	public String getHoldingChain() {
		return this.holdingChain;
	}

	public void setHoldingChain(String holdingChain) {
		this.holdingChain = holdingChain;
	}

	@Column(name = "BAL_STACK_CODE", length = 50)
	public String getBalStackCode() {
		return this.balStackCode;
	}

	public void setBalStackCode(String balStackCode) {
		this.balStackCode = balStackCode;
	}

}
