// default package
// Generated Sep 8, 2020 6:03:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBalanceStacks generated by hbm2java
 */
@Entity
@Table(name = "TBL_BALANCE_STACKS")
public class TblBalanceStacks implements java.io.Serializable {

	private BigDecimal balStackId;
	private String balStackName;
	private String balStackCode;
	private Date createdDate;
	private Date editedDate;

	public TblBalanceStacks() {
	}

	public TblBalanceStacks(BigDecimal balStackId, String balStackName, String balStackCode) {
		this.balStackId = balStackId;
		this.balStackName = balStackName;
		this.balStackCode = balStackCode;
	}

	public TblBalanceStacks(BigDecimal balStackId, String balStackName, String balStackCode, Date createdDate,
			Date editedDate) {
		this.balStackId = balStackId;
		this.balStackName = balStackName;
		this.balStackCode = balStackCode;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
	}

	@Id

	@Column(name = "BAL_STACK_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getBalStackId() {
		return this.balStackId;
	}

	public void setBalStackId(BigDecimal balStackId) {
		this.balStackId = balStackId;
	}

	@Column(name = "BAL_STACK_NAME", nullable = false, length = 200)
	public String getBalStackName() {
		return this.balStackName;
	}

	public void setBalStackName(String balStackName) {
		this.balStackName = balStackName;
	}

	@Column(name = "BAL_STACK_CODE", nullable = false, length = 50)
	public String getBalStackCode() {
		return this.balStackCode;
	}

	public void setBalStackCode(String balStackCode) {
		this.balStackCode = balStackCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDITED_DATE", length = 7)
	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

}
