// default package
// Generated Sep 7, 2020 4:22:51 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblBalanceStacksId generated by hbm2java
 */
@Embeddable
public class TblBalanceStacksId implements java.io.Serializable {

	private BigDecimal balStackId;
	private String balStackName;
	private String balStackCode;
	private Date createdDate;
	private Date editedDate;

	public TblBalanceStacksId() {
	}

	public TblBalanceStacksId(BigDecimal balStackId, String balStackName, String balStackCode) {
		this.balStackId = balStackId;
		this.balStackName = balStackName;
		this.balStackCode = balStackCode;
	}

	public TblBalanceStacksId(BigDecimal balStackId, String balStackName, String balStackCode, Date createdDate,
			Date editedDate) {
		this.balStackId = balStackId;
		this.balStackName = balStackName;
		this.balStackCode = balStackCode;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
	}

	@Column(name = "BAL_STACK_ID", nullable = false, precision = 0)
	public BigDecimal getBalStackId() {
		return this.balStackId;
	}

	public void setBalStackId(BigDecimal balStackId) {
		this.balStackId = balStackId;
	}

	@Column(name = "BAL_STACK_NAME", nullable = false, length = 200)
	public String getBalStackName() {
		return this.balStackName;
	}

	public void setBalStackName(String balStackName) {
		this.balStackName = balStackName;
	}

	@Column(name = "BAL_STACK_CODE", nullable = false, length = 50)
	public String getBalStackCode() {
		return this.balStackCode;
	}

	public void setBalStackCode(String balStackCode) {
		this.balStackCode = balStackCode;
	}

	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "EDITED_DATE", length = 7)
	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblBalanceStacksId))
			return false;
		TblBalanceStacksId castOther = (TblBalanceStacksId) other;

		return ((this.getBalStackId() == castOther.getBalStackId()) || (this.getBalStackId() != null
				&& castOther.getBalStackId() != null && this.getBalStackId().equals(castOther.getBalStackId())))
				&& ((this.getBalStackName() == castOther.getBalStackName())
						|| (this.getBalStackName() != null && castOther.getBalStackName() != null
								&& this.getBalStackName().equals(castOther.getBalStackName())))
				&& ((this.getBalStackCode() == castOther.getBalStackCode())
						|| (this.getBalStackCode() != null && castOther.getBalStackCode() != null
								&& this.getBalStackCode().equals(castOther.getBalStackCode())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getEditedDate() == castOther.getEditedDate())
						|| (this.getEditedDate() != null && castOther.getEditedDate() != null
								&& this.getEditedDate().equals(castOther.getEditedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBalStackId() == null ? 0 : this.getBalStackId().hashCode());
		result = 37 * result + (getBalStackName() == null ? 0 : this.getBalStackName().hashCode());
		result = 37 * result + (getBalStackCode() == null ? 0 : this.getBalStackCode().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getEditedDate() == null ? 0 : this.getEditedDate().hashCode());
		return result;
	}

}
