// default package
// Generated May 14, 2020 4:02:14 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblDownloadPins generated by hbm2java
 */
@Entity
@Table(name = "TBL_DOWNLOAD_PINS")
public class TblDownloadPins implements java.io.Serializable {

	private BigDecimal rowId;
	private String requestId;
	private int productId;
	private String cardSerial;
	private String cardPin;
	private String expireOn;

	public TblDownloadPins() {
	}

	public TblDownloadPins(BigDecimal rowId, String requestId, int productId, String cardSerial, String cardPin) {
		this.rowId = rowId;
		this.requestId = requestId;
		this.productId = productId;
		this.cardSerial = cardSerial;
		this.cardPin = cardPin;
	}

	public TblDownloadPins(BigDecimal rowId, String requestId, int productId, String cardSerial, String cardPin,
			String expireOn) {
		this.rowId = rowId;
		this.requestId = requestId;
		this.productId = productId;
		this.cardSerial = cardSerial;
		this.cardPin = cardPin;
		this.expireOn = expireOn;
	}

	@Id

	@Column(name = "ROW_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getRowId() {
		return this.rowId;
	}

	public void setRowId(BigDecimal rowId) {
		this.rowId = rowId;
	}

	@Column(name = "REQUEST_ID", nullable = false, length = 50)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Column(name = "PRODUCT_ID", nullable = false, precision = 8, scale = 0)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "CARD_SERIAL", nullable = false, length = 20)
	public String getCardSerial() {
		return this.cardSerial;
	}

	public void setCardSerial(String cardSerial) {
		this.cardSerial = cardSerial;
	}

	@Column(name = "CARD_PIN", nullable = false, length = 50)
	public String getCardPin() {
		return this.cardPin;
	}

	public void setCardPin(String cardPin) {
		this.cardPin = cardPin;
	}

	@Column(name = "EXPIRE_ON", length = 20)
	public String getExpireOn() {
		return this.expireOn;
	}

	public void setExpireOn(String expireOn) {
		this.expireOn = expireOn;
	}

}
