// default package
// Generated May 14, 2020 4:02:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblItopupProducts generated by hbm2java
 */
@Entity
@Table(name = "TBL_ITOPUP_PRODUCTS")
public class TblItopupProducts implements java.io.Serializable {

	private int rowId;
	private String providerName;
	private int providerAmount;
	private Integer itopupProductId;
	private Integer itopupType;
	private Date createdDate;
	private Date editedDate;
	private int prodActive;
	private Double commission;
	private String itopupMapProductId;

	public TblItopupProducts() {
	}

	public TblItopupProducts(int rowId, String providerName, int providerAmount, int prodActive) {
		this.rowId = rowId;
		this.providerName = providerName;
		this.providerAmount = providerAmount;
		this.prodActive = prodActive;
	}

	public TblItopupProducts(int rowId, String providerName, int providerAmount, Integer itopupProductId,
			Integer itopupType, Date createdDate, Date editedDate, int prodActive, Double commission,
			String itopupMapProductId) {
		this.rowId = rowId;
		this.providerName = providerName;
		this.providerAmount = providerAmount;
		this.itopupProductId = itopupProductId;
		this.itopupType = itopupType;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
		this.prodActive = prodActive;
		this.commission = commission;
		this.itopupMapProductId = itopupMapProductId;
	}

	@Id

	@Column(name = "ROW_ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getRowId() {
		return this.rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	@Column(name = "PROVIDER_NAME", nullable = false, length = 100)
	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "PROVIDER_AMOUNT", nullable = false, precision = 8, scale = 0)
	public int getProviderAmount() {
		return this.providerAmount;
	}

	public void setProviderAmount(int providerAmount) {
		this.providerAmount = providerAmount;
	}

	@Column(name = "ITOPUP_PRODUCT_ID", precision = 8, scale = 0)
	public Integer getItopupProductId() {
		return this.itopupProductId;
	}

	public void setItopupProductId(Integer itopupProductId) {
		this.itopupProductId = itopupProductId;
	}

	@Column(name = "ITOPUP_TYPE", precision = 8, scale = 0)
	public Integer getItopupType() {
		return this.itopupType;
	}

	public void setItopupType(Integer itopupType) {
		this.itopupType = itopupType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDITED_DATE", length = 7)
	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

	@Column(name = "PROD_ACTIVE", nullable = false, precision = 8, scale = 0)
	public int getProdActive() {
		return this.prodActive;
	}

	public void setProdActive(int prodActive) {
		this.prodActive = prodActive;
	}

	@Column(name = "COMMISSION", precision = 8, scale = 0)
	public Double getCommission() {
		return this.commission;
	}

	public void setCommission(Double commission) {
		this.commission = commission;
	}

	@Column(name = "ITOPUP_MAP_PRODUCT_ID", length = 100)
	public String getItopupMapProductId() {
		return this.itopupMapProductId;
	}

	public void setItopupMapProductId(String itopupMapProductId) {
		this.itopupMapProductId = itopupMapProductId;
	}

}
