// default package
// Generated Sep 8, 2020 6:03:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblServiceBalMapping generated by hbm2java
 */
@Entity
@Table(name = "TBL_SERVICE_BAL_MAPPING")
public class TblServiceBalMapping implements java.io.Serializable {

	private BigDecimal rowId;
	private BigDecimal serviceId;
	private BigDecimal balanceStackId;
	private Date createdDate;
	private String createdBy;

	public TblServiceBalMapping() {
	}

	public TblServiceBalMapping(BigDecimal rowId) {
		this.rowId = rowId;
	}

	public TblServiceBalMapping(BigDecimal rowId, BigDecimal serviceId, BigDecimal balanceStackId, Date createdDate,
			String createdBy) {
		this.rowId = rowId;
		this.serviceId = serviceId;
		this.balanceStackId = balanceStackId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "ROW_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getRowId() {
		return this.rowId;
	}

	public void setRowId(BigDecimal rowId) {
		this.rowId = rowId;
	}

	@Column(name = "SERVICE_ID", precision = 0)
	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "BALANCE_STACK_ID", precision = 0)
	public BigDecimal getBalanceStackId() {
		return this.balanceStackId;
	}

	public void setBalanceStackId(BigDecimal balanceStackId) {
		this.balanceStackId = balanceStackId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 11)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
