// default package
// Generated Sep 8, 2020 6:03:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblSims generated by hbm2java
 */
@Entity
@Table(name = "TBL_SIMS")
public class TblSims implements java.io.Serializable {

	private String simNumber;
	private BigDecimal simBal;
	private Date simLatestUpdate;
	private String providerCode;
	private Integer simStatus;
	private String simCom;
	private Integer minBalance;
	private BigDecimal maxBalance;
	private Integer autoTransfer;
	private Integer simMaster;
	private String server;
	private Date latestSendSms;
	private Integer simGroup;

	public TblSims() {
	}

	public TblSims(String simNumber) {
		this.simNumber = simNumber;
	}

	public TblSims(String simNumber, BigDecimal simBal, Date simLatestUpdate, String providerCode, Integer simStatus,
			String simCom, Integer minBalance, BigDecimal maxBalance, Integer autoTransfer, Integer simMaster,
			String server, Date latestSendSms, Integer simGroup) {
		this.simNumber = simNumber;
		this.simBal = simBal;
		this.simLatestUpdate = simLatestUpdate;
		this.providerCode = providerCode;
		this.simStatus = simStatus;
		this.simCom = simCom;
		this.minBalance = minBalance;
		this.maxBalance = maxBalance;
		this.autoTransfer = autoTransfer;
		this.simMaster = simMaster;
		this.server = server;
		this.latestSendSms = latestSendSms;
		this.simGroup = simGroup;
	}

	@Id

	@Column(name = "SIM_NUMBER", unique = true, nullable = false, length = 50)
	public String getSimNumber() {
		return this.simNumber;
	}

	public void setSimNumber(String simNumber) {
		this.simNumber = simNumber;
	}

	@Column(name = "SIM_BAL", precision = 0)
	public BigDecimal getSimBal() {
		return this.simBal;
	}

	public void setSimBal(BigDecimal simBal) {
		this.simBal = simBal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIM_LATEST_UPDATE", length = 7)
	public Date getSimLatestUpdate() {
		return this.simLatestUpdate;
	}

	public void setSimLatestUpdate(Date simLatestUpdate) {
		this.simLatestUpdate = simLatestUpdate;
	}

	@Column(name = "PROVIDER_CODE", length = 10)
	public String getProviderCode() {
		return this.providerCode;
	}

	public void setProviderCode(String providerCode) {
		this.providerCode = providerCode;
	}

	@Column(name = "SIM_STATUS", precision = 8, scale = 0)
	public Integer getSimStatus() {
		return this.simStatus;
	}

	public void setSimStatus(Integer simStatus) {
		this.simStatus = simStatus;
	}

	@Column(name = "SIM_COM", length = 10)
	public String getSimCom() {
		return this.simCom;
	}

	public void setSimCom(String simCom) {
		this.simCom = simCom;
	}

	@Column(name = "MIN_BALANCE", precision = 8, scale = 0)
	public Integer getMinBalance() {
		return this.minBalance;
	}

	public void setMinBalance(Integer minBalance) {
		this.minBalance = minBalance;
	}

	@Column(name = "MAX_BALANCE", precision = 0)
	public BigDecimal getMaxBalance() {
		return this.maxBalance;
	}

	public void setMaxBalance(BigDecimal maxBalance) {
		this.maxBalance = maxBalance;
	}

	@Column(name = "AUTO_TRANSFER", precision = 8, scale = 0)
	public Integer getAutoTransfer() {
		return this.autoTransfer;
	}

	public void setAutoTransfer(Integer autoTransfer) {
		this.autoTransfer = autoTransfer;
	}

	@Column(name = "SIM_MASTER", precision = 8, scale = 0)
	public Integer getSimMaster() {
		return this.simMaster;
	}

	public void setSimMaster(Integer simMaster) {
		this.simMaster = simMaster;
	}

	@Column(name = "SERVER", length = 20)
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_SEND_SMS", length = 7)
	public Date getLatestSendSms() {
		return this.latestSendSms;
	}

	public void setLatestSendSms(Date latestSendSms) {
		this.latestSendSms = latestSendSms;
	}

	@Column(name = "SIM_GROUP", precision = 8, scale = 0)
	public Integer getSimGroup() {
		return this.simGroup;
	}

	public void setSimGroup(Integer simGroup) {
		this.simGroup = simGroup;
	}

}
