// default package
// Generated Sep 8, 2020 6:03:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblServiceKeys generated by hbm2java
 */
@Entity
@Table(name = "TBL_SERVICE_KEYS")
public class TblServiceKeys implements java.io.Serializable {

	private BigDecimal rowId;
	private int serviceId;
	private Integer serviceType;
	private String serviceKey;
	private String serviceVersion;
	private Date updateKeyAt;
	private Integer serviceKeyStatus;
	private String serviceIp;
	private String serviceSmsOtpContent;
	private String serviceName;

	public TblServiceKeys() {
	}

	public TblServiceKeys(BigDecimal rowId, int serviceId, String serviceKey) {
		this.rowId = rowId;
		this.serviceId = serviceId;
		this.serviceKey = serviceKey;
	}

	public TblServiceKeys(BigDecimal rowId, int serviceId, Integer serviceType, String serviceKey,
			String serviceVersion, Date updateKeyAt, Integer serviceKeyStatus, String serviceIp,
			String serviceSmsOtpContent, String serviceName) {
		this.rowId = rowId;
		this.serviceId = serviceId;
		this.serviceType = serviceType;
		this.serviceKey = serviceKey;
		this.serviceVersion = serviceVersion;
		this.updateKeyAt = updateKeyAt;
		this.serviceKeyStatus = serviceKeyStatus;
		this.serviceIp = serviceIp;
		this.serviceSmsOtpContent = serviceSmsOtpContent;
		this.serviceName = serviceName;
	}

	@Id

	@Column(name = "ROW_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getRowId() {
		return this.rowId;
	}

	public void setRowId(BigDecimal rowId) {
		this.rowId = rowId;
	}

	@Column(name = "SERVICE_ID", nullable = false, precision = 8, scale = 0)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "SERVICE_TYPE", precision = 8, scale = 0)
	public Integer getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	@Column(name = "SERVICE_KEY", nullable = false, length = 50)
	public String getServiceKey() {
		return this.serviceKey;
	}

	public void setServiceKey(String serviceKey) {
		this.serviceKey = serviceKey;
	}

	@Column(name = "SERVICE_VERSION", length = 20)
	public String getServiceVersion() {
		return this.serviceVersion;
	}

	public void setServiceVersion(String serviceVersion) {
		this.serviceVersion = serviceVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_KEY_AT", length = 7)
	public Date getUpdateKeyAt() {
		return this.updateKeyAt;
	}

	public void setUpdateKeyAt(Date updateKeyAt) {
		this.updateKeyAt = updateKeyAt;
	}

	@Column(name = "SERVICE_KEY_STATUS", precision = 8, scale = 0)
	public Integer getServiceKeyStatus() {
		return this.serviceKeyStatus;
	}

	public void setServiceKeyStatus(Integer serviceKeyStatus) {
		this.serviceKeyStatus = serviceKeyStatus;
	}

	@Column(name = "SERVICE_IP", length = 100)
	public String getServiceIp() {
		return this.serviceIp;
	}

	public void setServiceIp(String serviceIp) {
		this.serviceIp = serviceIp;
	}

	@Column(name = "SERVICE_SMS_OTP_CONTENT", length = 500)
	public String getServiceSmsOtpContent() {
		return this.serviceSmsOtpContent;
	}

	public void setServiceSmsOtpContent(String serviceSmsOtpContent) {
		this.serviceSmsOtpContent = serviceSmsOtpContent;
	}

	@Column(name = "SERVICE_NAME", length = 100)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

}
