// default package
// Generated Sep 8, 2020 6:03:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblServices generated by hbm2java
 */
@Entity
@Table(name = "TBL_SERVICES")
public class TblServices implements java.io.Serializable {

	private int serviceId;
	private String serviceFullName;
	private String serviceCode;
	private Date createdDate;
	private Date updateDate;
	private String serviceScKey;
	private Integer serviceStatus;
	private String serviceSmsOtpContent;
	private BigDecimal isMainService;

	public TblServices() {
	}

	public TblServices(int serviceId) {
		this.serviceId = serviceId;
	}

	public TblServices(int serviceId, String serviceFullName, String serviceCode, Date createdDate, Date updateDate,
			String serviceScKey, Integer serviceStatus, String serviceSmsOtpContent, BigDecimal isMainService) {
		this.serviceId = serviceId;
		this.serviceFullName = serviceFullName;
		this.serviceCode = serviceCode;
		this.createdDate = createdDate;
		this.updateDate = updateDate;
		this.serviceScKey = serviceScKey;
		this.serviceStatus = serviceStatus;
		this.serviceSmsOtpContent = serviceSmsOtpContent;
		this.isMainService = isMainService;
	}

	@Id

	@Column(name = "SERVICE_ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "SERVICE_FULL_NAME", length = 100)
	public String getServiceFullName() {
		return this.serviceFullName;
	}

	public void setServiceFullName(String serviceFullName) {
		this.serviceFullName = serviceFullName;
	}

	@Column(name = "SERVICE_CODE", length = 50)
	public String getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "SERVICE_SC_KEY", length = 50)
	public String getServiceScKey() {
		return this.serviceScKey;
	}

	public void setServiceScKey(String serviceScKey) {
		this.serviceScKey = serviceScKey;
	}

	@Column(name = "SERVICE_STATUS", precision = 8, scale = 0)
	public Integer getServiceStatus() {
		return this.serviceStatus;
	}

	public void setServiceStatus(Integer serviceStatus) {
		this.serviceStatus = serviceStatus;
	}

	@Column(name = "SERVICE_SMS_OTP_CONTENT", length = 500)
	public String getServiceSmsOtpContent() {
		return this.serviceSmsOtpContent;
	}

	public void setServiceSmsOtpContent(String serviceSmsOtpContent) {
		this.serviceSmsOtpContent = serviceSmsOtpContent;
	}

	@Column(name = "IS_MAIN_SERVICE", precision = 0)
	public BigDecimal getIsMainService() {
		return this.isMainService;
	}

	public void setIsMainService(BigDecimal isMainService) {
		this.isMainService = isMainService;
	}

}
