package springboot.hbn.entities;

// default package
// Generated Oct 14, 2019 4:33:28 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * TblAccounts generated by hbm2java
 */
@Entity
@Table(name = "TBL_ACCOUNTS")
@DynamicUpdate
@DynamicInsert
public class TblAccounts implements java.io.Serializable {

	@Override
	public String toString() {
		return "TblAccounts [accId=" + accId + "\r accPhone=" + accPhone + "\r accEmail=" + accEmail
				+ "\r accActivePhone=" + accActivePhone + "\r accActiveEmail=" + accActiveEmail + "\r activePhoneDate="
				+ activePhoneDate + "\r activeEmailDate=" + activeEmailDate + "\r createdDate=" + createdDate
				+ "\r accIdNumber=" + accIdNumber + "\r accIdName=" + accIdName + "\r displayName=" + displayName
				+ "\r birthday=" + birthday + "\r avatar=" + avatar + "\r balance=" + balance + "\r blockBalance="
				+ blockBalance + "\r balanceChain=" + balanceChain + "\r latestUpdate=" + latestUpdate + "\r accStatus="
				+ accStatus + "\r latestUpdatePassword=" + latestUpdatePassword + "\r expirePassAt=" + expirePassAt
				+ "\r requireChangeExpPass=" + requireChangeExpPass + "\r forceChangePass=" + forceChangePass
				+ "\r forceLogin=" + forceLogin + "\r accIndentify=" + accIndentify + "\r loginPassword="
				+ loginPassword + "]";
	}

	private BigDecimal accId;
	private String accPhone;
	private String accEmail;
	private Integer accActivePhone;
	private Integer accActiveEmail;
	private Date activePhoneDate;
	private Date activeEmailDate;
	private Date createdDate;
	private String accIdNumber;
	private String accIdName;
	private String displayName;
	private Integer birthday;
	private String avatar;
	private BigDecimal balance;
	private BigDecimal blockBalance;
	private String balanceChain;
	private Date latestUpdate;
	private Integer accStatus;
	private Date latestUpdatePassword;
	private Date expirePassAt;
	private Integer requireChangeExpPass;
	private Integer forceChangePass;
	private Integer forceLogin;
	private String accIndentify;
	private String loginPassword;
	private Integer userId;
	private Integer receiveNotify;
	private Integer loginFrom;
	private BigDecimal bonusBalance;
	private Integer ownByServiceId;

	@Column(name = "OWN_BY_SERVICE_ID", precision = 8, scale = 0)
	public Integer getOwnByServiceId() {
		return ownByServiceId;
	}

	public void setOwnByServiceId(Integer ownByServiceId) {
		this.ownByServiceId = ownByServiceId;
	}

	public TblAccounts() {
	}

	public TblAccounts(BigDecimal accId, String accIndentify, String loginPassword) {
		this.accId = accId;
		this.accIndentify = accIndentify;
		this.loginPassword = loginPassword;
	}

	public TblAccounts(BigDecimal accId, String accPhone, String accEmail, Integer accActivePhone,
			Integer accActiveEmail, Date activePhoneDate, Date activeEmailDate, Date createdDate, String accIdNumber,
			String accIdName, String displayName, Integer birthday, String avatar, BigDecimal balance,
			BigDecimal blockBalance, String balanceChain, Date latestUpdate, Integer accStatus,
			Date latestUpdatePassword, Date expirePassAt, Integer requireChangeExpPass, Integer forceChangePass,
			Integer forceLogin, String accIndentify, String loginPassword) {
		this.accId = accId;
		this.accPhone = accPhone;
		this.accEmail = accEmail;
		this.accActivePhone = accActivePhone;
		this.accActiveEmail = accActiveEmail;
		this.activePhoneDate = activePhoneDate;
		this.activeEmailDate = activeEmailDate;
		this.createdDate = createdDate;
		this.accIdNumber = accIdNumber;
		this.accIdName = accIdName;
		this.displayName = displayName;
		this.birthday = birthday;
		this.avatar = avatar;
		this.balance = balance;
		this.blockBalance = blockBalance;
		this.balanceChain = balanceChain;
		this.latestUpdate = latestUpdate;
		this.accStatus = accStatus;
		this.latestUpdatePassword = latestUpdatePassword;
		this.expirePassAt = expirePassAt;
		this.requireChangeExpPass = requireChangeExpPass;
		this.forceChangePass = forceChangePass;
		this.forceLogin = forceLogin;
		this.accIndentify = accIndentify;
		this.loginPassword = loginPassword;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "retal_seq")
	@SequenceGenerator(name = "retal_seq", sequenceName = "SEQ_TBL_ACCOUNTS")
	@Column(name = "ACC_ID", unique = true, nullable = false, precision = 0)
	public BigDecimal getAccId() {
		return this.accId;
	}

	public void setAccId(BigDecimal accId) {
		this.accId = accId;
	}

	@Column(name = "ACC_PHONE", length = 20)
	public String getAccPhone() {
		return this.accPhone;
	}

	public void setAccPhone(String accPhone) {
		this.accPhone = accPhone;
	}

	@Column(name = "ACC_EMAIL", length = 100)
	public String getAccEmail() {
		return this.accEmail;
	}

	public void setAccEmail(String accEmail) {
		this.accEmail = accEmail;
	}

	@Column(name = "ACC_ACTIVE_PHONE", precision = 8, scale = 0)
	public Integer getAccActivePhone() {
		return this.accActivePhone;
	}

	public void setAccActivePhone(Integer accActivePhone) {
		this.accActivePhone = accActivePhone;
	}

	@Column(name = "ACC_ACTIVE_EMAIL", precision = 8, scale = 0)
	public Integer getAccActiveEmail() {
		return this.accActiveEmail;
	}

	public void setAccActiveEmail(Integer accActiveEmail) {
		this.accActiveEmail = accActiveEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVE_PHONE_DATE", length = 7)
	public Date getActivePhoneDate() {
		return this.activePhoneDate;
	}

	public void setActivePhoneDate(Date activePhoneDate) {
		this.activePhoneDate = activePhoneDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVE_EMAIL_DATE", length = 7)
	public Date getActiveEmailDate() {
		return this.activeEmailDate;
	}

	public void setActiveEmailDate(Date activeEmailDate) {
		this.activeEmailDate = activeEmailDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7, insertable = false)
	@CreationTimestamp
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "ACC_ID_NUMBER", length = 20)
	public String getAccIdNumber() {
		return this.accIdNumber;
	}

	public void setAccIdNumber(String accIdNumber) {
		this.accIdNumber = accIdNumber;
	}

	@Column(name = "ACC_ID_NAME", length = 100)
	public String getAccIdName() {
		return this.accIdName;
	}

	public void setAccIdName(String accIdName) {
		this.accIdName = accIdName;
	}

	@Column(name = "DISPLAY_NAME", length = 100)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "BIRTHDAY", precision = 8, scale = 0)
	public Integer getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Integer birthday) {
		this.birthday = birthday;
	}

	@Column(name = "AVATAR", length = 500)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "BALANCE", precision = 0)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Column(name = "BLOCK_BALANCE", precision = 0)
	public BigDecimal getBlockBalance() {
		return this.blockBalance;
	}

	public void setBlockBalance(BigDecimal blockBalance) {
		this.blockBalance = blockBalance;
	}

	@Column(name = "BALANCE_CHAIN", length = 50)
	public String getBalanceChain() {
		return this.balanceChain;
	}

	public void setBalanceChain(String balanceChain) {
		this.balanceChain = balanceChain;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_UPDATE", length = 7)
	public Date getLatestUpdate() {
		return this.latestUpdate;
	}

	public void setLatestUpdate(Date latestUpdate) {
		this.latestUpdate = latestUpdate;
	}

	@Column(name = "ACC_STATUS", precision = 8, scale = 0)
	public Integer getAccStatus() {
		return this.accStatus;
	}

	public void setAccStatus(Integer accStatus) {
		this.accStatus = accStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_UPDATE_PASSWORD", length = 7)
	public Date getLatestUpdatePassword() {
		return this.latestUpdatePassword;
	}

	public void setLatestUpdatePassword(Date latestUpdatePassword) {
		this.latestUpdatePassword = latestUpdatePassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRE_PASS_AT", length = 7)
	public Date getExpirePassAt() {
		return this.expirePassAt;
	}

	public void setExpirePassAt(Date expirePassAt) {
		this.expirePassAt = expirePassAt;
	}

	@Column(name = "REQUIRE_CHANGE_EXP_PASS", precision = 8, scale = 0)
	public Integer getRequireChangeExpPass() {
		return this.requireChangeExpPass;
	}

	public void setRequireChangeExpPass(Integer requireChangeExpPass) {
		this.requireChangeExpPass = requireChangeExpPass;
	}

	@Column(name = "FORCE_CHANGE_PASS", precision = 8, scale = 0)
	public Integer getForceChangePass() {
		return this.forceChangePass;
	}

	public void setForceChangePass(Integer forceChangePass) {
		this.forceChangePass = forceChangePass;
	}

	@Column(name = "FORCE_LOGIN", precision = 8, scale = 0)
	public Integer getForceLogin() {
		return this.forceLogin;
	}

	public void setForceLogin(Integer forceLogin) {
		this.forceLogin = forceLogin;
	}

	@Column(name = "ACC_INDENTIFY", nullable = false, length = 100)
	public String getAccIndentify() {
		return this.accIndentify;
	}

	public void setAccIndentify(String accIndentify) {
		this.accIndentify = accIndentify;
	}

	@Column(name = "LOGIN_PASSWORD", nullable = false, length = 32)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	@Column(name = "USER_ID", precision = 8, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "RECEIVE_NOTIFY", precision = 8, scale = 0)
	public Integer getReceiveNotify() {
		return this.receiveNotify;
	}

	public void setReceiveNotify(Integer receiveNotify) {
		this.receiveNotify = receiveNotify;
	}

	@Column(name = "LOGIN_FROM", precision = 8, scale = 0)
	public Integer getLoginFrom() {
		return this.loginFrom;
	}

	public void setLoginFrom(Integer loginFrom) {
		this.loginFrom = loginFrom;
	}

	@Column(name = "BONUS_BALANCE", precision = 0)
	public BigDecimal getBonusBalance() {
		return this.bonusBalance;
	}

	public void setBonusBalance(BigDecimal bonusBalance) {
		this.bonusBalance = bonusBalance;
	}
}
