package springboot.hbn.entities;

// default package
// Generated Oct 23, 2019 6:12:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * TblBills generated by hbm2java
 */
@Entity
@Table(name = "TBL_BILLS")
@DynamicInsert
@DynamicUpdate
public class TblBills implements java.io.Serializable {

	private BigDecimal billId;
	private String targetNumber;
	private int billAmount;
	private Date billImportDate;
	private Integer billStatus;
	private int billMonth;
	private Date updateDate;
	private String billTargetName;
	private int billType;
	private String billFileName;
	private Date expireDate;
	private Integer previousStatus;
	private String createdBy;

	public TblBills() {
	}

	public TblBills(BigDecimal billId, String targetNumber, int billAmount, Date billImportDate, int billMonth) {
		this.billId = billId;
		this.targetNumber = targetNumber;
		this.billAmount = billAmount;
		this.billImportDate = billImportDate;
		this.billMonth = billMonth;
	}

	public TblBills(BigDecimal billId, String targetNumber, int billAmount, Date billImportDate, Integer billStatus,
			int billMonth, Date updateDate) {
		this.billId = billId;
		this.targetNumber = targetNumber;
		this.billAmount = billAmount;
		this.billImportDate = billImportDate;
		this.billStatus = billStatus;
		this.billMonth = billMonth;
		this.updateDate = updateDate;
	}

	@Id
	@Column(name = "BILL_ID", unique = true, nullable = false, precision = 0)
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "retal_seq")
	@SequenceGenerator(name = "retal_seq", sequenceName = "SEQ_BILLS")
	public BigDecimal getBillId() {
		return this.billId;
	}

	public void setBillId(BigDecimal billId) {
		this.billId = billId;
	}

	@Column(name = "TARGET_NUMBER", nullable = false, length = 50)
	public String getTargetNumber() {
		return this.targetNumber;
	}

	public void setTargetNumber(String targetNumber) {
		this.targetNumber = targetNumber;
	}

	@Column(name = "BILL_AMOUNT", nullable = false, precision = 8, scale = 0)
	public int getBillAmount() {
		return this.billAmount;
	}

	public void setBillAmount(int billAmount) {
		this.billAmount = billAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BILL_IMPORT_DATE", nullable = false, length = 7)
	public Date getBillImportDate() {
		return this.billImportDate;
	}

	public void setBillImportDate(Date billImportDate) {
		this.billImportDate = billImportDate;
	}

	@Column(name = "BILL_STATUS", precision = 8, scale = 0)
	public Integer getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(Integer billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "BILL_MONTH", nullable = false, precision = 8, scale = 0)
	public int getBillMonth() {
		return this.billMonth;
	}

	public void setBillMonth(int billMonth) {
		this.billMonth = billMonth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "BILL_TARGET_NAME", length = 50)
	public String getBillTargetName() {
		return this.billTargetName;
	}

	public void setBillTargetName(String billTargetName) {
		this.billTargetName = billTargetName;
	}

	@Column(name = "BILL_TYPE", nullable = false, precision = 8, scale = 0)
	public int getBillType() {
		return this.billType;
	}

	public void setBillType(int billType) {
		this.billType = billType;
	}

	@Column(name = "BILL_FILE_NAME", length = 100)
	public String getBillFileName() {
		return this.billFileName;
	}

	public void setBillFileName(String billFileName) {
		this.billFileName = billFileName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRE_DATE", length = 7)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Column(name = "PREVIOUS_STATUS", precision = 8, scale = 0)
	public Integer getPreviousStatus() {
		return this.previousStatus;
	}

	public void setPreviousStatus(Integer previousStatus) {
		this.previousStatus = previousStatus;
	}

	@Column(name = "CREATED_BY", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
}
