package springboot.hbn.entities;

// default package
// Generated Oct 24, 2019 3:18:20 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * TblTransactions generated by hbm2java
 */
@Entity
@Table(name = "TBL_TRANSACTIONS")
@DynamicInsert
@DynamicUpdate
public class TblTransactions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Override
	public String toString() {
		return "TblTransactions [requestId=" + requestId + "\r transactionType=" + transactionType + "\r requestAmt="
				+ requestAmt + "\r createdDate=" + createdDate + "\r updatedDate=" + updatedDate + "\r finalStatus="
				+ finalStatus + "\r remark=" + remark + "\r trnFee=" + trnFee + "\r billId=" + billId
				+ "\r targetNumber=" + targetNumber + "\r accId=" + accId + "\r accUserName=" + accUserName
				+ "\r agentNumber=" + agentNumber + "\r agentRpMessage=" + agentRpMessage + "\r agentBalBef="
				+ agentBalBef + "\r agentBalAf=" + agentBalAf + "\r accBalBf=" + accBalBf + "\r accBalAf=" + accBalAf
				+ "]";
	}

	private String requestId;
	private Integer transactionType;
	private BigDecimal requestAmt;
	private Date createdDate;
	private Date updatedDate;
	private Integer finalStatus;
	private String remark;
	private Integer trnFee;
	private BigDecimal billId;
	private String targetNumber;
	private BigDecimal accId;
	private String accUserName;
	private String agentNumber;
	private String agentRpMessage;
	private BigDecimal agentBalBef;
	private BigDecimal agentBalAf;
	private BigDecimal accBalBf;
	private BigDecimal accBalAf;
	private Integer userId;

	public TblTransactions() {
	}

	public TblTransactions(String requestId) {
		this.requestId = requestId;
	}

	public TblTransactions(String requestId, Integer transactionType, BigDecimal requestAmt, Date createdDate,
			Date updatedDate, Integer finalStatus, String remark, Integer trnFee, BigDecimal accId,
			String accUserName) {
		this.requestId = requestId;
		this.transactionType = transactionType;
		this.requestAmt = requestAmt;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.finalStatus = finalStatus;
		this.remark = remark;
		this.trnFee = trnFee;
		this.accId = accId;
		this.accUserName = accUserName;

	}

	@Id

	@Column(name = "REQUEST_ID", unique = true, nullable = false, length = 50)
	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	@Column(name = "TRANSACTION_TYPE", precision = 8, scale = 0)
	public Integer getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(Integer transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "REQUEST_AMT", precision = 0)
	public BigDecimal getRequestAmt() {
		return this.requestAmt;
	}

	public void setRequestAmt(BigDecimal requestAmt) {
		this.requestAmt = requestAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "FINAL_STATUS", precision = 8, scale = 0)
	public Integer getFinalStatus() {
		return this.finalStatus;
	}

	public void setFinalStatus(Integer finalStatus) {
		this.finalStatus = finalStatus;
	}

	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "TRN_FEE", precision = 8, scale = 0)
	public Integer getTrnFee() {
		return this.trnFee;
	}

	public void setTrnFee(Integer trnFee) {
		this.trnFee = trnFee;
	}

	@Column(name = "BILL_ID", precision = 0)
	public BigDecimal getBillId() {
		return this.billId;
	}

	public void setBillId(BigDecimal billId) {
		this.billId = billId;
	}

	@Column(name = "TARGET_NUMBER", length = 20)
	public String getTargetNumber() {
		return this.targetNumber;
	}

	public void setTargetNumber(String targetNumber) {
		this.targetNumber = targetNumber;
	}

	@Column(name = "ACC_ID", precision = 0)
	public BigDecimal getAccId() {
		return this.accId;
	}

	public void setAccId(BigDecimal accId) {
		this.accId = accId;
	}

	@Column(name = "ACC_USER_NAME", length = 100)
	public String getAccUserName() {
		return this.accUserName;
	}

	public void setAccUserName(String accUserName) {
		this.accUserName = accUserName;
	}

	@Column(name = "AGENT_NUMBER", length = 20)
	public String getAgentNumber() {
		return this.agentNumber;
	}

	public void setAgentNumber(String agentNumber) {
		this.agentNumber = agentNumber;
	}

	@Column(name = "AGENT_RP_MESSAGE", length = 500)
	public String getAgentRpMessage() {
		return this.agentRpMessage;
	}

	public void setAgentRpMessage(String agentRpMessage) {
		this.agentRpMessage = agentRpMessage;
	}

	@Column(name = "AGENT_BAL_BEF", precision = 0)
	public BigDecimal getAgentBalBef() {
		return this.agentBalBef;
	}

	public void setAgentBalBef(BigDecimal agentBalBef) {
		this.agentBalBef = agentBalBef;
	}

	@Column(name = "AGENT_BAL_AF", precision = 0)
	public BigDecimal getAgentBalAf() {
		return this.agentBalAf;
	}

	public void setAgentBalAf(BigDecimal agentBalAf) {
		this.agentBalAf = agentBalAf;
	}

	@Column(name = "ACC_BAL_BF", precision = 0)
	public BigDecimal getAccBalBf() {
		return this.accBalBf;
	}

	public void setAccBalBf(BigDecimal accBalBf) {
		this.accBalBf = accBalBf;
	}

	@Column(name = "ACC_BAL_AF", precision = 0)
	public BigDecimal getAccBalAf() {
		return this.accBalAf;
	}

	public void setAccBalAf(BigDecimal accBalAf) {
		this.accBalAf = accBalAf;
	}

	@Column(name = "USER_ID", precision = 8, scale = 0)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}
