package springboot.hbn.entities;

// default package
// Generated Nov 4, 2019 5:30:30 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
@DynamicUpdate
@DynamicInsert
public class Users implements java.io.Serializable {

	@Override
	public String toString() {
		return "Users [id=" + id + ", username=" + username + ", password=" + password + ", email=" + email
				+ ", firstname=" + firstname + ", lastname=" + lastname + ", phone=" + phone + ", gender=" + gender
				+ ", partnerId=" + partnerId + ", userType=" + userType + ", userBalance=" + userBalance
				+ ", latestUpdateBal=" + latestUpdateBal + ", userStatus=" + userStatus + "]";
	}

	private long id;
	private String username;
	private String password;
	private String email;
	private String firstname;
	private String lastname;
	private String phone;
	private long gender;
	private long partnerId;
	private long userType;
	private long userBalance;
	private Date latestUpdateBal;
	private int userStatus;

	public Users() {
	}

	public Users(long id, String username, String password, String email, String firstname, String lastname,
			String phone, long gender, long partnerId, long userType, long userBalance) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.gender = gender;
		this.partnerId = partnerId;
		this.userType = userType;
		this.userBalance = userBalance;
	}

	public Users(long id, String username, String password, String email, String firstname, String lastname,
			String phone, long gender, long partnerId, long userType, long userBalance, Date latestUpdateBal) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.gender = gender;
		this.partnerId = partnerId;
		this.userType = userType;
		this.userBalance = userBalance;
		this.latestUpdateBal = latestUpdateBal;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "USERNAME", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FIRSTNAME", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", nullable = false)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "PHONE", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "GENDER", nullable = false, precision = 10, scale = 0)
	public long getGender() {
		return this.gender;
	}

	public void setGender(long gender) {
		this.gender = gender;
	}

	@Column(name = "PARTNER_ID", nullable = false, precision = 10, scale = 0)
	public long getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(long partnerId) {
		this.partnerId = partnerId;
	}

	@Column(name = "USER_TYPE", nullable = false, precision = 10, scale = 0)
	public long getUserType() {
		return this.userType;
	}

	public void setUserType(long userType) {
		this.userType = userType;
	}

	@Column(name = "USER_BALANCE", nullable = false, precision = 0)
	public long getUserBalance() {
		return this.userBalance;
	}

	public void setUserBalance(long userBalance) {
		this.userBalance = userBalance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LATEST_UPDATE_BAL", length = 7)
	public Date getLatestUpdateBal() {
		return this.latestUpdateBal;
	}

	public void setLatestUpdateBal(Date latestUpdateBal) {
		this.latestUpdateBal = latestUpdateBal;
	}

	@Column(name = "USER_STATUS", nullable = false, precision = 8, scale = 0)
	public int getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(int userStatus) {
		this.userStatus = userStatus;
	}
}
